version: '3.7'
services:
  db:
    container_name: container-db
    build:
      context: postgres
    environment:
      POSTGRES_USERS: ${KONG_DB_USERNAME}:${KONG_DB_PASSWORD}|${KONGA_DB_USERNAME}:${KONGA_DB_PASSWORD}
      POSTGRES_DATABASES: ${KONG_DB_NAME}:${KONG_DB_USERNAME}|${KONGA_DB_NAME}:${KONGA_DB_USERNAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_DB_USERNAME}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
    - persist_volume:/var/lib/postgresql/data
    networks:
    - kong-network

  kong-migrations:
    container_name: container-kong-migrations
    image: kong:latest
    entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_DB_HOST}
      KONG_PG_DATABASE: ${KONG_DB_NAME}
      KONG_PG_USER: ${KONG_DB_USERNAME}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
    depends_on:
    - db
    networks:
    - kong-network
    restart: on-failure

  kong:
    container_name: container-kong
    image: kong:latest
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_DB_HOST}
      KONG_PG_DATABASE: ${KONG_DB_NAME}
      KONG_PG_USER: ${KONG_DB_USERNAME}
      KONG_PG_PASSWORD: ${KONG_DB_PASSWORD}
      KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
      KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
      KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
      KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
      KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
    restart: unless-stopped
    ports:
    - $KONG_PROXY_PORT:8000
    - $KONG_PROXY_SSL_PORT:8443
    - mode: host
      target: $KONG_PROXY_ADMIN_API_PORT
      published: $KONG_PROXY_ADMIN_API_PORT
    - mode: host
      target: $KONG_PROXY_ADMIN_SSL_API_PORT
      published: $KONG_PROXY_ADMIN_SSL_API_PORT
    networks:
    - kong-network

  konga:
    container_name: container-konga
    image: pantsel/konga
    environment:
      TOKEN_SECRET: ${KONGA_TOKEN_SECRET}
      DB_ADAPTER: ${KONG_DATABASE}
      DB_HOST: ${KONGA_DB_HOST}
      DB_PORT: ${KONGA_DB_PORT}
      DB_DATABASE: ${KONGA_DB_NAME}
      DB_USER: ${KONGA_DB_USERNAME}
      DB_PASSWORD: ${KONGA_DB_PASSWORD}
      NODE_ENV: ${KONGA_ENV}
      KONGA_HOOK_TIMEOUT: 10000
    restart: unless-stopped
    ports:
    - $KONGA_PORT:1337
    depends_on:
    - db
    networks:
    - kong-network

volumes:
  persist_volume:

networks:
  kong-network:
    external: true
